service: location-info-collection

frameworkVersion: "2"

useDotenv: true

plugins:
  - serverless-offline
  - serverless-step-functions

provider:
  name: aws
  runtime: python3.8
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    S3_BUCKET: ${env:S3_BUCKET}
    POST_LAMBDA_ARN: ${env:POST_LAMBDA_ARN}
  lambdaHashingVersion: 20201221
  stage: production
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource:
        - "arn:aws:dynamodb:*"
        - "arn:aws:s3:::*"

functions:
  post:
    handler: handler.post
    events:
      - http:
          path: /post
          method: post
          cors: true

  output:
    handler: handler.output_csv
    events:
      - schedule: cron(0 21 * * ? *)

stepFunctions:
  stateMachines:
    StateMachinePostTooManyRequestError:
      name: PostTooManyRequestErrorStateMachine
      definition:
        StartAt: Post
        States:
          Post:
            Type: Task
            Resource: ${env:POST_LAMBDA_ARN}
            Retry:
              - ErrorEquals:
                  - TooManyRequestError
                IntervalSeconds: 60
                MaxAttempts: 30
            End: true
