service: location-info-collection

frameworkVersion: "2"

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    # S3_BUCKET:
  lambdaHashingVersion: 20201221
  stage: production
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource:
        - "arn:aws:dynamodb:*"
        - "arn:aws:s3:::*"

functions:
  # rateHandler:
  #   handler: handler.run
  #   events:
  #     # Invoke Lambda function every minute
  #     # - schedule: rate(1 minute)
  # cronHandler:
  #   handler: handler.run
  #   events:
  #     # Invoke Lambda function every 2nd minute from Mon-Fri
  #     # - schedule: cron(0/2 * ? * MON-FRI *)

  post:
    handler: handler.post
    events:
      - http:
          path: /post
          method: post
          cors: true
