service: location-info-collection

frameworkVersion: "2"

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    S3_BUCKET: ${env:S3_BUCKET}
  lambdaHashingVersion: 20201221
  stage: production
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource:
        - "arn:aws:dynamodb:*"
        - "arn:aws:s3:::*"

functions:
  post:
    handler: handler.post
    events:
      - http:
          path: /post
          method: post
          cors: true

  output:
    handler: handler.output_csv
    events:
      - schedule: cron(0 21 * * ? *)

  bucket_list:
    handler: handler.bucket_list
    events:
      - http:
          path: /bucket_list
          method: get
          cors: true
          response:
            headers:
              Content-Type: application/json;charset=UTF-8

  download_csv:
    handler: handler.download_csv
    events:
      - http:
          path: /download_csv/{file}
          method: get
          cors: true
          request:
            parameters:
              paths:
                file: true
          response:
            headers:
              Content-Type: application/json;charset=UTF-8
